// <auto-generated />
using EveMarketSpider.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EveMarketSpider.Migrations
{
    [DbContext(typeof(EveContext))]
    [Migration("20200519065914_init_marketgroup")]
    partial class init_marketgroup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("EveMarketEntities.MarketGroup", b =>
                {
                    b.Property<int>("MarketGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MarketGroupId");

                    b.ToTable("MarketGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
